name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v4
    - run: cargo test

  test_no_std:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - run: rustup target add thumbv6m-none-eabi
    - uses: actions/checkout@v4
    - run: cargo check --target thumbv6m-none-eabi --no-default-features

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - run: rustup update stable
    - uses: actions/checkout@v4
    - run: cargo fmt -- --check
